# ============================================================================
# ArgoCD Application - Stage Environment
# Deploys ScoutFlow to stage namespace with automated sync for QA testing
# ============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scoutflow-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  sources:
    - repoURL: https://github.com/omerbh7/scoutflow-app
      targetRevision: main
      path: helm/scoutflow
      helm:
        valueFiles:
          - $values/environments/stage/values.yaml
    
    - repoURL: https://github.com/omerbh7/scoutflow-gitops
      targetRevision: main
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ServerSideApply=false
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m